### ISSUE TITLE
Checksum doesn't match error

### ISSUE THREAD

**Issue by sanjeevk1410** [wercker/step-maven#13]
I forked the sample-maven-step repo and created an app on wercker with it.
After getting the message
"Hello from the Maven Wercker Step
For information on how to use this step, please review the documentation in the Wercker Marketplace,
or visit https://github.com/wercker/step-maven
22:18:23: Downloading Maven"

I see this error:
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 261 100 261 0 0 860 0 --:--:-- --:--:-- --:--:-- 861
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 265 100 265 0 0 768 0 --:--:-- --:--:-- --:--:-- 768
failed: 22:18:24: checksum does not match

for the box definition in wercker.yml, I changed it to openjdk, maven, and some other jre's too but nothing worked.

Here is my wercker.yml: https://github.com/sanjeevk1410/sample-maven-step/blob/master/wercker.yml

**Comment by bashaus** [comment]
I was having this issue too, and I believe that it's been solved in this PR:
https://github.com/wercker/step-maven/pull/16

It's currently only merged to master, so you'll have to wait until it gets made into a deployed version on wercker, but that shouldn't be long.

**Comment by sanjeevk1410** [comment]
Thanks for your help @bashaus!

**Comment by tothatt** [comment]
Hi!

Actually I solved it by adding a version parameter to the maven step.

Regards,
Attila
